apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tweet-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tweet-service
  minReplicas: 1       # Minimum aantal pods
  maxReplicas: 5       # Maximum aantal pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60